version: "3.8"

services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: etymology_bot
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - .:/app
    networks:
      - bot_network

networks:
  bot_network:
    driver: bridge
